sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_install:
  - composer selfupdate
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - pear install pear/PHP_CodeSniffer-2.9.1
  - phpenv rehash

install:
  - composer install

script:
  - phing -f build.xml
